### ISSUE TITLE
Implement IE support

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/clustr#10]
Downsized images should work.

**Comment by dhcole** [comment]
Here's an implementation that uses the Google image charts API, good through 2015: 8f284432e444d6ed82e6e87f77403e32d82a1947

It uses the fill and stroke colors passed to it.
![](https://img.skitch.com/20120721-cej5jh1d51tpi69c2ux4rge9hd.jpg)

Docs on this Google method:
- [sample circle](http://chart.apis.google.com/chart?cht=it&chs=200x200&chco=336699FF,00000000,00000000&chf=bg,s,00000000&ext=.png)
- [gmaps implementation](http://gmaps-utility-library.googlecode.com/svn/trunk/mapiconmaker/1.1/examples/markericonoptions-wizard.html)
- [undocs](http://www.john-am.com/2010/07/making-circles-in-google-charts-undocumented-chart-types-for-google-charts/)

**Comment by tmcw** [comment]
One tweak - canvas circles are 0.5 opacity fill, the google ones are 100% right now.

**Comment by dhcole** [comment]
I think transparency is a problem because the stroke is achieved by layering two solid circles. The background circle would bleed through the transparency of the foreground one. Plus some old ie does not support alpha png right? We could adjust the default colors match better though.

Do you have any thoughts on this? Am I missing some other approach?

**Comment by tmcw** [comment]
Gotcha, good enough then. Nice work on this.
